name: Deploy to Vercel

on:
  push:
    branches:
      - main # Change this if your target branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify Node.js version 18

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
